### ISSUE TITLE
any chance of a release?

### ISSUE THREAD

**Issue by cpackham** [zonque/pxa-impedance-matcher#5]
Hi,

Firstly thanks for this. I posted [a question](http://lists.infradead.org/pipermail/linux-arm-kernel/2015-October/379342.html) on the linux-arm mailing list a while back and they pointed me over here. It totally solves my problem.

One thing I'd like to be able to do is use this as part of a meta-build system (like buildroot, but actually a custom in-house thing). While building from a git repo is doable it's easier if we can download a tarball that way we can benefit from local mirrors and pin to particular versions.

I can (and have) generate a tarball myself with git archive but the first problem I run into when building from this tarball is that genver.sh assumes there is a git repo to generate the version from.

Would the addition of a `make dist` target be accepted?

**Comment by zonque** [comment]
I never actually intended to have a real release infrastructure for this, because I initially thought of this project as some sort of blueprint for people to build their own tool from. But if you're saying that the code as such works for you and your boards, I can certainly release a tagged version. It's nice to hear this project has real users, btw :)

So yes, if you want to add that target, just send a PR. I can then make a release.

**Comment by cpackham** [comment]
The way I'm using this I add a board-foo.c file and a Makefile.config.foo and yes it works quite well for my purposes.

I've submitted a couple of PRs for this and some build issues I was having.

**Comment by zonque** [comment]
v1 is released now, and archives can be downloaded from GitHub.
